// THIS FILE IS AUTOGENERATED
// Source: wavedash/src/convex/constants/sdkConstants.ts

/**
 * Default values used by Game SDKs
 * These values are used externally, any changes need to be reflected in the Wavedash SDKs
 *
 * We use int values here rather than strings to speed up data marshalling in SDK calls
 */

// ========== GAME ENGINE ==========
export const GAME_ENGINE = {
	GODOT: 'GODOT',
	UNITY: 'UNITY',
	UNREAL: 'UNREAL',
	CUSTOM: 'CUSTOM'
} as const;

// ========== LOBBIES ==========
const LOBBY_EXPIRY_HOURS = 24;

export const LOBBY_DEFAULTS = {
	MAX_PLAYERS: 100,
	EXPIRY_HOURS: LOBBY_EXPIRY_HOURS,
	EXPIRY_MS: LOBBY_EXPIRY_HOURS * 60 * 60 * 1000
} as const;

export const LOBBY_VISIBILITY = {
	PUBLIC: 0,
	FRIENDS_ONLY: 1,
	PRIVATE: 2
} as const;

export const LOBBY_MESSAGE_MAX_LENGTH = 500;

// ========== LEADERBOARDS ==========
export const LEADERBOARD_SORT_ORDER = {
	ASC: 0,
	DESC: 1
} as const;

export const LEADERBOARD_DISPLAY_TYPE = {
	NUMERIC: 0,
	TIME_SECONDS: 1,
	TIME_MILLISECONDS: 2
} as const;

// ========== USER GENERATED CONTENT ==========
export const UGC_TYPE = {
	SCREENSHOT: 0,
	VIDEO: 1,
	COMMUNITY: 2,
	GAME_MANAGED: 3, // Managed completely by the game, user doesn't edit
	OTHER: 4
} as const;

export const UGC_VISIBILITY = {
	PUBLIC: 0,
	FRIENDS_ONLY: 1,
	PRIVATE: 2
} as const;

export const UGC_UPLOAD_STATUS = {
	NOT_STARTED: 0,
	UPLOADING: 1,
	FAILED: 2,
	COMPLETED: 3
} as const;

export const REMOTE_STORAGE = {
	DEFAULT_LIMIT_BYTES: 1024 * 1024 * 1024, // 1GB default limit

	// Rate limiting configuration
	UPLOADS_PER_MINUTE: 30, // Max uploads per minute (burst protection)
	UPLOADS_PER_HOUR: 300 // Max uploads per hour (sustained usage)
} as const;

export const P2P_SIGNALING_MESSAGE_TYPE = {
	OFFER: 'offer',
	ANSWER: 'answer',
	ICE_CANDIDATE: 'ice-candidate'
} as const;

export const GAME_AUTHORITY = {
	CLIENT: 0,
	SERVER: 1
} as const;

export const STAT_TYPE = {
	INTEGER: 0,
	FLOAT: 1,
	AVG_RATE: 2
} as const;

export const GAMEPLAY_HEARTBEAT = {
	INTERVAL_MS: 30_000,	// send heartbeat to backend every 30s
	TIMEOUT_MS: 90_000		// mark user as disconnected after 90s of no heartbeats
} as const;
