// THIS FILE IS AUTOGENERATED
// Source: wavedash/src/convex/constants/sdkConstants.ts

/**
 * Default values used by Game SDKs
 * These values are used externally, any changes need to be reflected in the Wavedash SDKs
 *
 * We use int values here rather than strings to speed up data marshalling in SDK calls
 */

// ========== LOBBIES ==========
const LOBBY_EXPIRY_HOURS = 24;

export const LOBBY_DEFAULTS = {
	MAX_PLAYERS: 100,
	EXPIRY_HOURS: LOBBY_EXPIRY_HOURS,
	EXPIRY_MS: LOBBY_EXPIRY_HOURS * 60 * 60 * 1000
} as const;

export const LOBBY_TYPE = {
	PUBLIC: 0,
	FRIENDS_ONLY: 1,
	PRIVATE: 2
} as const;

// ========== LEADERBOARDS ==========
export const LEADERBOARD_SORT_ORDER = {
	ASC: 0,
	DESC: 1
} as const;

export const LEADERBOARD_DISPLAY_TYPE = {
	NUMERIC: 0,
	TIME_SECONDS: 1,
	TIME_MILLISECONDS: 2
} as const;

// ========== USER GENERATED CONTENT ==========
export const UGC_CONTENT_TYPE = {
	SCREENSHOT: 0,
	VIDEO: 1,
	COMMUNITY: 2,
	GAME_MANAGED: 3, // Managed completely by the game, user doesn't edit
	OTHER: 4
} as const;

export const UGC_VISIBILITY = {
	PUBLIC: 0,
	FRIENDS_ONLY: 1,
	PRIVATE: 2
} as const;
