/**
 * SDK-to-Engine Events
 *
 * Defines all events that the SDK sends to the game engine.
 * These are maintained manually in the SDK (not autogenerated from backend).
 *
 * The game engine listens for these events to react to SDK updates.
 */

export const WavedashEvents = {
  // Lobby events
  LOBBY_MESSAGE: "LobbyMessage",
  LOBBY_JOINED: "LobbyJoined",
  LOBBY_KICKED: "LobbyKicked", // player was removed from lobby (kicked by host or disconnected)
  LOBBY_USERS_UPDATED: "LobbyUsersUpdated",
  LOBBY_DATA_UPDATED: "LobbyDataUpdated",
  LOBBY_INVITE: "LobbyInvite", // received an invite to join a lobby

  // P2P events
  P2P_CONNECTION_ESTABLISHED: "P2PConnectionEstablished", // connection to peer is ready
  P2P_CONNECTION_FAILED: "P2PConnectionFailed", // connection to peer failed
  P2P_PEER_DISCONNECTED: "P2PPeerDisconnected", // peer disconnected

  // Backend connection events
  BACKEND_CONNECTED: "BackendConnected", // connected to Convex backend
  BACKEND_DISCONNECTED: "BackendDisconnected", // disconnected from Convex backend
  BACKEND_RECONNECTING: "BackendReconnecting" // attempting to reconnect to backend

  // TODO: Future events to implement
  // P2P_CONNECTION_REQUESTED: 'P2PConnectionRequested', // for now we always connect all lobby members
} as const;
