/**
 * SDK-to-Engine Signals
 * 
 * Defines all signals that the SDK sends to the game engine.
 * These are maintained manually in the SDK (not autogenerated from backend).
 * 
 * The game engine listens for these signals to react to SDK events.
 */

export const Signals = {
  // Lobby signals
  LOBBY_MESSAGE: 'LobbyMessage',
  LOBBY_KICKED: 'LobbyKicked', // player was removed from lobby either by host or network issue
  LOBBY_JOINED: 'LobbyJoined',
  LOBBY_USERS_UPDATED: 'LobbyUsersUpdated',
  LOBBY_DATA_UPDATED: 'LobbyDataUpdated',
  
  // P2P signals
  P2P_MESSAGE: 'P2PMessage',
  P2P_CONNECTION_ESTABLISHED: 'P2PConnectionEstablished', // connection to peer is ready
  P2P_CONNECTION_FAILED: 'P2PConnectionFailed', // connection to peer failed
  P2P_PEER_DISCONNECTED: 'P2PPeerDisconnected', // peer disconnected
  
  // TODO: Future signals to implement
  // LOBBY_INVITE: 'LobbyInvite',
  // P2P_CONNECTION_REQUESTED: 'P2PConnectionRequested', // for now we always connect all lobby members
} as const;
